[package]
name = "AoC2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.3.1"
combinatorial = "0.2.0"
itertools = "0.12.0"
ndarray = "0.15.6"
proceed = "0.1.0"
